### PR TITLE
Attempt to fix for MacOS users (copy environment table)

### PR DESCRIPTION
**Pull request by ddavness**
The IPC layer for Unix uses process environments that aren't copied to the slave processes - this should help, I guess?

This probably relates to https://github.com/discordjs/RPC/issues/54

## Other changes:
- Added a setting which defines a custom timeout if you're forcing launching Discord (it was hardcoded which is not ideal) - defaults to 30 seconds.

- Added comments to the config file - it's a slightly questionable way to do this but I don't see a choice for a better way (JSON doesn't natively allow comments).

- Developer-wise, `standard` is now a dev dependency of roPresence. Code has been standardized.

- Version bump to 1.0.5

**Will be kept as a draft until a macOS user confirms to me this works!**

### CODE REVIEW

**Comment by sasial-roblox** [comment]
Does work for windows; awaiting mac.
Not a fan of all this:
image

**Comment by sasial-dev** [comment]
Works on windows.
Am not a fan of the terminal JSON.

**Comment by ddavness** [comment]
I know, it's out there for debugging reasons - I actually intend to remove it in a future commit.

Diff reference:
https://github.com/JiveOff/roPresence/pull/21/files#diff-168726dbe96b3ce427e7fedce31bb0bcR24-R27

**Comment by sasial-dev** [comment]
Got it.

**Comment by ddavness** [comment]
@theLMGN, @Monkey8729, @GameAddict7 - please give me feedback on whether this works on your machines. Thank you!

**Comment by JiveOff** [comment]
Any news?

**Comment by ddavness** [comment]
As of now, nothing.

I'm going to check whether the MacOS behaviour can be applied to Linux aswell.

**Comment by JiveOff** [comment]
Alrighty. I will see if I can find other MacOS users. Le 2 oct. 2019 00:35, David Duque <notifications@github.com> a écrit :As of now, nothing.
I'm going to check whether the MacOS behaviour can be applied to Linux aswell.

**Comment by ddavness** [comment]
## Update: Linux presents the same behavior of macOS

Since they're both Unix derived, I can safely assume this patch applies to both environments:
I was able to reproduce the bug described in #12 and #18, and succeed with the patch presented.

image
*(At left, the current version, at the right, with the patch).*

If we disable the patch we get this:

a

See how the environment variable `XDG_RUNTIME_DIR` (which `discord-rpc` relies on) isn't passed from the master process to the slave process.

Since that this fix works, I'm marking this as ready for review.

**Comment by ddavness** [comment]
This should do the trick! :slightly_smiling_face:

**Pull request merged**
