### PR TITLE
Handling Discord connection failure

### PR DESCRIPTION
**Pull request by ddavness**
This happens when Discord hasn't been launched yet. That way we'll proceed by notifying the user of such.

As a "beta", clicking on the notification might launch Discord for you, but your mileage may vary. (Depends on the installation, and only for Windows at the moment).

### CODE REVIEW

**Comment by ddavness** [comment]
**Update:** Unfortunately a default Discord installation cannot be opened by simply typing `Discord.exe` into the terminal, and failure isn't silent (at least for Windows 7). Need to look at this further.

**Comment by ddavness** [comment]
Note: Don't merge yet. There's some stuff I need to get figured out before you do so.

Current issues:
- roPresence is launched and discord is not; Discord is forcefully launched and with success; however for some reason the second login still fails.

- A setting on `config.json` isn't set to the default.

**Comment by ddavness** [comment]
After this painful debugging session, this seems to work and OK to review.

**Comment by ddavness** [comment]
But please note, there are quite a few changes here. Read this commits desc for more information

**Comment by ddavness** [comment]
Ready for review and eventual merging.

**Review by JiveOff — APPROVED** [review]
Thank you for this pull request!
I will merge now and standardize it tomorrow.

Thanks again for this PR, I will create a release also tomorrow.

**Pull request merged**
