### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by sasial-dev**
Changes:
-

- Reverted index.js to 1.0.3.1 so it is compatible with mac users.
  - Changed section in code so that instead of going to the API to get the Roblox username each time; it justs set's the activity.
- Added Mac .bat file equivalent (Will get someone to test but I believe it works.)
- Added Text in the console:
image
image

- Removed Express web server.
- Replaced with Application. (Coded in pure HTML)

Welcome Page
----

image 
Notification happened to pop up at the same time.

Settings Page
----

image 
Will probably add more settings in the future.

Shutdown Page
----

image Auto Closes window + console after 10 seconds.

### CODE REVIEW

**Comment by sasial-dev** [comment]
Let me know if you have any questions or issues.

**Comment by JiveOff** [comment]
@ddavness What do you think?
@sasial-roblox I noticed some "illegal" changes such as the address where the presences are requested. Please revert it back to vps1.jiveoff.fr:3000

**Comment by ddavness** [comment]
1.0.4 has been introduced by #8 - I prefer to actually take some time investigating the issue rather than attempting a rollback. I might have one idea that might be related with children processes, but I'll probably want some volunteers using Mac machines to test eventual fixes.

**Related issues:** #12 and #18

**Comment by sasial-dev** [comment]
@JiveOff Didn't see that; Just changed now above.
@ddavness Rollback for now; then the next version can be back to your stuff.

**Comment by ddavness** [comment]
Based on https://github.com/discordjs/RPC/issues/54, it might be an env issue (which would make sense) - I am trying to push out a fix for that - see #21 - so that we don't need to revert.

Any mac users that can test this out: @theLMGN, @Monkey8729, @GameAddict7, please do the following - make sure you have git and nodejs installed:

`git clone https://github.com/ddavness/roPresence`
`cd roPresence`
`node index.js`

Leave comments about this over the pull request #21

**Comment by sasial-dev** [comment]
^ If you don't have git; just download it as a zip file and go to the terminal from there.

**Comment by sasial-dev** [comment]
Let me know of your progress; and I'll add it to my PR if it works.
Might combine #17 as well as yours (#21) to make it really easy for @JiveOff.

**Comment by sasial-dev** [comment]
For people who cannot use Github:
~~*Cough* @GameAddict7 *Cough.*~~
image

**Comment by foxt** [comment]
Working for me (macOS)

**Comment by sasial-dev** [comment]
Nice!
#21? @theLMGN

**Comment by foxt** [comment]
@sasial-roblox I don't have a tmp envar on my machine, so that's probably the issue 
image

**Comment by ddavness** [comment]
I'm confused now - are we discussing this PR in particular the #21 PR?
You aren't expected to have that particular envar - seemingly there are a lot of possible envars for Unix temporary folder:

`XDG_RUNTIME_DIR`, `TMPDIR`, `TMP`, `TEMP`

It's likely that your system has the first envar. Anyways, comments about the pull request 21 should be made there!

**Comment by sasial-dev** [comment]
Completely re-doing this with electron.
Please disregard this PR for now.

**Pull request closed without merging**
